### ISSUE TITLE
Wiki example spec possible incorrect mixin

### ISSUE THREAD

**Issue by blackjable** [thejameskyle/bootcamp#105]
Hi,

I tried to get the example from the wiki running with no success. Sass transpiler was complaining about an undefined mixin define.

Inspecting the lib code base I could not find anywhere the mixin define. I could find a describe mixin. Having used Jasmine before I assume that is what was meant.

Was this a typo in the wiki?

Regards,

Jamie

**Comment by thejameskyle** [comment]
I don't see anything in the wiki that refers to a `define` mixin

**Comment by morewry** [comment]
![bootcamp](https://cloud.githubusercontent.com/assets/1043291/7894012/f05bcf70-0618-11e5-9e7b-beacbf431f68.png)
